# Generated by Django 4.1.7 on 2023-04-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
    ]
