# Generated by Django 4.1.7 on 2023-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_section', '0002_remove_category_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
