# Generated by Django 4.1.7 on 2023-04-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budget_section', '0003_alter_budget_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
