# Generated by Django 4.1.7 on 2023-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budget_section', '0004_alter_budget_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
