# Generated by Django 4.1.7 on 2023-04-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_section', '0005_budget_slug_category_slug_transaction_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
