# Generated by Django 4.1.2 on 2022-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
