# Generated by Django 4.1.2 on 2022-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_myapp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='img',
            field=models.ImageField(upload_to='my_apps'),
        ),
    ]
