# Generated by Django 4.1.7 on 2023-04-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_myapp_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyApp',
        ),
    ]
