# Generated by Django 4.1.7 on 2023-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
