# Generated by Django 4.1.7 on 2023-04-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsaccount',
            old_name='account_holder',
            new_name='user',
        ),
    ]
