# Generated by Django 4.1.7 on 2023-04-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
