# Generated by Django 4.1.2 on 2022-12-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='repetition_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
